apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: olde22479
  name: odoo-database  
  labels:
    app: odoo
    tier: backend
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        tier: backend
    spec:
      containers:
      - image: postgres:10.4
        name: postgres
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgresdb
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: olde22479pv1
