# -*- coding: utf-8 -*-
{
'name': 'Sunat - Emisión electrónica Peruana',
'description': "Addon para enviar documentos a sunat",
'author': "ROCKSCRIPTS",
    'website': "https://instagram.com/rockscripts",
    'summary': "Emisión de documentos contables a Sunat a través de punto de venta, sitio web de comercio y en sección de facturación.",
    'version': '0.1',
    "license": "OPL-1",
    'price':'320',
    'currency':'EUR',
    'support': 'rockscripts@gmail.com',
    'category': 'module_category_account_voucher',
    "images": ["images/banner.png"],
    'depends': [
                'base',
                'account',                
                'delivery',                
                'account_debit_note',
                'account_payment_group',
                'account_payment',
                'website',
                'website_sale',
                'point_of_sale',
               ],
    'data': [    
                'security/ir.model.access.csv',        
                'views/res_company.xml',
                'views/res_partner.xml',
                'views/product.xml',
                'views/account_journal.xml',
                'views/account_tax.xml',
                'views/account_move.xml',
                'views/inventory.xml',
                'views/website.xml',
                'views/general.xml',
                'views/account_move_reversal.xml',
                'views/account_move_debit.xml',
                'data/pe.datas.catalog59.xml',
                'views/sunat_catalogs.xml',                
                #'security/ir.model.access.csv',
            ],
    'qweb': [
                'static/src/xml/screens/pos_screen_client_edit.xml',
                'static/src/xml/pos_ticket.xml',
            ],
    'demo': [],
    'installable': True,
}